name: Composer

on: 
  push:

jobs:
  setup:
      name: Setup
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: PHP check
          run: php -v

        - name: Composer check
          run: composer -v