name: PHPUnit

on: 
  push:

env:
  CACHE_TAG: v1
  VENDOR_CACHE_ID: cache_vendor_dependencies
  NODE_MODULES_CACHE_ID: cache_node_modules_dependencies
  
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install composer packages & cache vendor directory
        uses: ./.github/actions/cache-vendor-dependencies
        with:
          cache_tag: ${{ env.CACHE_TAG }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install npm packages & cache node_modules
        uses: ./.github/actions/cache-node_modules-dependencies
        with:
          cache_tag: ${{ env.CACHE_TAG }}

  test:
    name: PHPUnit
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # php-version: ['8.0', '8.1', '8.2']
        # wp-version:  ['master', '6.2', '6.1', '6.0', '5.9']
        php-version: [ '8.0' ]
        wp-version: [ '6.2' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup -> PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}


      - name: Install composer packages & cache vendor directory
        uses: ./.github/actions/cache-vendor-dependencies
        with:
          cache_tag: ${{ env.CACHE_TAG }}

      - name: Install npm packages & cache node_modules
        uses: ./.github/actions/cache-node_modules-dependencies
        with:
          cache_tag: ${{ env.CACHE_TAG }}

      - name: Generate .wp-env.override.json
        run: |
          echo '{"config": {},"core": "WordPress/WordPress#${{ matrix.wp-version }}","env": {},"mappings": {},"phpVersion": "${{ matrix.php-version }}","plugins": ["."],"themes": []}' > .wp-env.override.json

      - name: Start wp-env
        run: npm run wp-env start -- --xdebug=coverage

      - name: Run test suite
        run: npm run test:env

      - name: Check cache
        run: |
          ls -la ${{ github.workspace }}/
          ls -la ${{ github.workspace }}/coverage/reports/
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          directory: ${{ github.workspace }}/coverage/reports/
          verbose: true