name: PHPUnit

on: 
  push:

env:
  CACHE_TAG: v1
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache dependencies
        id: cache_dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/vendor
            ${{ github.workspace }}/.npm
          key: ${{ runner.os }}-dependencies-${{ env.CACHE_TAG }}-${{ hashFiles('**/composer.lock') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-${{ env.CACHE_TAG }}-
            ${{ runner.os }}-dependencies-
            ${{ runner.os }}

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-scripts --no-progress
          npm ci --ignore-scripts

  test:
    name: PHPUnit
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.0', '8.1', '8.2']
    steps:
      - name: Setup -> PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xdebug, dom

      - name: Checkout
        uses: actions/checkout@v3
      

      - name: Restore dependencies cache
        id: cache_dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/vendor
            ${{ github.workspace }}/.npm
          key: ${{ runner.os }}-dependencies-${{ env.CACHE_TAG }}-${{ hashFiles('**/composer.lock') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-${{ env.CACHE_TAG }}-
            ${{ runner.os }}-dependencies-
            ${{ runner.os }}

      - name: Install composer packages
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-scripts --no-progress

      - name: Install npm packages
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      
      - name: pwd
        run: pwd

      - name: ls -la
        run: ls -la

      - name: package.json
        run: cat package.json

      - name: check npm cmd
        run: npm run --version

      - name: Start wp-env
        run: npm run wp-env start --update

      - name: Run test suite
        run: npm run test:env